### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by blacky0x0** [untu/comedy#9]
Great framework! Is there any ideas what will be implemented later?
It could be something like https://www.testcontainers.org/ROADMAP.md
It's not an issue just a suggestion.

**Comment by weekens** [comment]
Thanks! Yeah, of course there is a roadmap, at least in my head. This includes:

- [ ]  More optimized message marshalling (BSON, Smile or whatever is the fastest);
- [ ]  Hot code deployment on remote actors;
- [ ]  Automatic actor clustering according to the current load;
- [ ]  Affinity-based message routing to clustered actors;

...and more.

I'll put this to Upcoming Features section in Getting Started guide in nearest time.

**Comment by weekens** [comment]
Added [Upcoming Features](https://github.com/untu/comedy#upcoming-features) section.
